services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arduino-rirau-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
