"""Descrição da alteração

Revision ID: 29498c5a9e4a
Revises: 016f7dcd0ec1
Create Date: 2025-08-03 16:27:21.493166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29498c5a9e4a'
down_revision: Union[str, Sequence[str], None] = '016f7dcd0ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
