"""Add user_id to alarms

Revision ID: 41f5c470453e
Revises: 4228b0866b6a
Create Date: 2025-08-13 11:55:04.773025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f5c470453e'
down_revision: Union[str, Sequence[str], None] = '4228b0866b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'alarms', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_alarms_days_alarm_id'), 'alarms_days', ['alarm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarms_days_alarm_id'), table_name='alarms_days')
    op.drop_constraint(None, 'alarms', type_='foreignkey')
    op.drop_column('alarms', 'user_id')
    # ### end Alembic commands ###
